#run the model here


#something


#end of day we want stats
#NUMBER OF PATIENTS WHO LEFT BECAUSE SATISFACTION TOO LOW
#NUMBER OF PATIENTS IN CLINIC THAT DAY
#AVERAGE WAIT TIME FOR HEIGHT AND WEIGHT
#AVERAGE WAIT TIME FOR CONSULTATION 1
#AVERAGE WAIT TIME FOR CONSULTATION 2
#AVERAGE WAIT TIME FOR BLOODS
#AVERAGE TIME START TO FINISH
#AVERAGE TOTAL WAIT TIMES
#DURATIONS TOO?

def count_day_data(XXXXXXX)
    #maths here?
    return(XXXXXXX)


